# Generated by Django 5.2.6 on 2025-09-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='topic',
            field=models.CharField(choices=[('philosophy', 'Философия'), ('family', 'Семья'), ('state', 'Государство'), ('cooking', 'Кулинария'), ('love', 'Любовь'), ('life', 'Жизнь')], default='', max_length=50, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
