# Generated by Django 5.2.6 on 2025-09-14 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='topic',
            field=models.CharField(choices=[('philosophy', 'Философия'), ('family', 'Семья'), ('state', 'Государство'), ('cooking', 'Кулинария'), ('love', 'Любовь'), ('life', 'Жизнь'), ('unknown', 'Не указано')], default='unknown', max_length=50, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Вес'),
        ),
    ]
