# Generated by Django 5.2.6 on 2025-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_topic_alter_quote_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(error_messages='Такая цитата уже существует', unique=True, verbose_name='Текст цитаты'),
        ),
    ]
